### ISSUE TITLE
What is the license of this?

### ISSUE THREAD

**Issue by KOLANICH** [NikethReddy/LZO_Compression-on-GPU-s-OpenCL#1]

**Comment by NikethBoReddy** [comment]
There is no license, feel free to use it for any academic or commercial purposes as you see fit. It would be helpful if you could include a citation for the same though.

**Comment by KOLANICH** [comment]
Thank you, but unfortunately `there is no license` is equal to `proprietary` in jurisdictions having copyright laws. If you want to allow everyone to do anything, you can add a license equivalent (some jurisdictions have no ways to assign a work to public domain other than expiration of copyright in 90 years after the death of author, but public domain like licenses are licenses, so should work, also they contain clauses disclaiming liability) to public domain dedication. I usually use [Unlicense](https://github.com/IQAndreas/markdown-licenses/blob/master/unlicense.md), but FSF recommends [CC0](https://raw.githubusercontent.com/idleberg/Creative-Commons-Markdown/master/4.0/zero.markdown) on the basis that it was more "tested in courts".

**Comment by NikethBoReddy** [comment]
I'll add one over the weekend then :)
